title = "gitleaks config — placeholders only"
[allowlist]
  description = "Placeholders allowed"
  regexes = ['''(PLACEHOLDER|DUMMY|REDACTED|EXAMPLE)_?(KEY|SECRET|TOKEN)''']

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api|secret|key|token)[\s:=]+[A-Za-z0-9_\-]{16,}'''
entropy = 3.5
keywords = ["api","key","secret","token"]
