services:
  - type: web
    name: bthwani-backend
    runtime: node
    plan: free
    branch: main
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
