name: 🧪 Tests & Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: 📥 Install dependencies
      run: npm ci
      
    - name: 🧪 Run tests with coverage
      run: npm test -- --coverage --watchAll=false --passWithNoTests
      
    - name: 📊 Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        
    - name: 📈 Generate coverage report
      run: |
        echo "📊 Coverage Summary:"
        npm test -- --coverage --watchAll=false --passWithNoTests --coverageReporters=text-summary
        
    - name: 🎯 Check coverage thresholds
      run: |
        npm test -- --coverage --watchAll=false --passWithNoTests --coverageReporters=text-summary | grep -E "(Statements|Branches|Functions|Lines)"
        
  quality:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: 📥 Install dependencies
      run: npm ci
      
    - name: 🔍 Run linting
      run: npm run lint --if-present
      
    - name: 📝 Check formatting
      run: npm run format:check --if-present
      
    - name: 🚀 Build check
      run: npm run build --if-present
      
  security:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔒 Run security audit
      run: npm audit --audit-level=moderate
      
    - name: 🛡️ Check for known vulnerabilities
      run: npm audit --audit-level=high
      
  notification:
    runs-on: ubuntu-latest
    needs: [test, quality, security]
    if: always()
    
    steps:
    - name: 📧 Notify on failure
      if: failure()
      run: |
        echo "❌ Tests failed! Check the logs for details."
        
    - name: 🎉 Notify on success
      if: success()
      run: |
        echo "✅ All checks passed successfully!"
        
    - name: 📊 Coverage status
      if: always()
      run: |
        echo "📈 Current coverage status:"
        echo "Target: 70%"
        echo "Current: 18.11%"
        echo "Status: Needs improvement"
