# Alertmanager Configuration - BTW-OBS-004

global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'

# Define notification templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  receiver: 'default'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
      group_wait: 0s
      repeat_interval: 5m

    # High priority alerts
    - match:
        severity: high
      receiver: 'high-alerts'
      repeat_interval: 30m

    # Medium priority alerts
    - match:
        severity: medium
      receiver: 'medium-alerts'
      repeat_interval: 2h

    # Low priority alerts
    - match:
        severity: low
      receiver: 'low-alerts'
      repeat_interval: 24h

# Inhibition rules - suppress certain alerts when others are firing
inhibit_rules:
  # Suppress warnings if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Suppress individual component alerts if service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '(HighErrorRate|HighLatency|.*)'
    equal: ['service']

# Receiver definitions
receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://localhost:5000/alerts'

  - name: 'critical-alerts'
    slack_configs:
      - channel: '#bthwani-critical'
        title: '🔴 CRITICAL: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true
    
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        description: '{{ .GroupLabels.alertname }}'
    
    webhook_configs:
      - url: 'http://localhost:5000/alerts/critical'

  - name: 'high-alerts'
    slack_configs:
      - channel: '#bthwani-alerts'
        title: '🟠 HIGH: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true
    
    webhook_configs:
      - url: 'http://localhost:5000/alerts/high'

  - name: 'medium-alerts'
    slack_configs:
      - channel: '#bthwani-alerts'
        title: '🟡 MEDIUM: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true

  - name: 'low-alerts'
    slack_configs:
      - channel: '#bthwani-monitoring'
        title: '🟢 LOW: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true

