# Prometheus configuration for BThwani - BTW-OBS-004

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bthwani-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # BThwani Backend
  - job_name: 'bthwani-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # MongoDB Exporter
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # NGINX
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
