apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/your-org/mern-app'
    targetRevision: main
    path: k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mern

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
